export const styleSheet={
    // navBarContainer:{
    //     display:'flex',
    //     flexDirection:"row",
    //     width:"100%",
    //     height:"100%",
    //     backgroundColor:"#ECEAE9",
    //     alignItems:"center",
    //     justifyContent:"center",
    //     position:"absolute",
    // },
    navTitle:{
        position:'absolute',
        left:"1%",
        display:'flex',
        alignItems:"center",
        justifyContent:'center',
        width:"20%",
        height:"100%",
        top:"0",
        bottom:"0",
        margin:"auto",
    },
    listOfNavBars:{
        position:"absolute",
        display:"flex",
        flexDirection:"row",
        right:"0",
        width:"50%",
        height:"100%",
        alignItems:'center',
        justifyContent:"center",
        transition:'all 1s',
    },
    navBtns:{
        display:"flex",
        flexDirection:"row",
        height:"80%",
        width:"40%",
        alignItems:"center",
        justifyContent:"center",
        backgroundColor:"#CCD4B0",
        borderRadius:"5px",
        marginLeft:"2%",
        marginRight:"2%",
    },
    listInNav:{
        display:"flex",
        textDecoration:"none"
    },
    ulChildContainer:{
        position:"absolute",
        display:"flex",
        flexDirection:"row",
        right:"0",
        width:"100%",
        height:"100%",
        alignItems:'center',
        justifyContent:"end",
        transition:'all 1s',
    },
    setAdminBtn:{
        display:"flex",
        flexDirection:"row",
        height:"80%",
        width:"10%",
        alignItems:"center",
        justifyContent:"center",
        backgroundColor:"#CCD4B0",
        borderRadius:"5px",
        marginLeft:"2%",
        marginRight:"2%",
    }
}